version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: raynara
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: portfoliodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./backend
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=portfoliodb;Username=raynara;Password=secret123

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
